[project]
name = "opt100"
version = "0.1.0"
description = "opt100+ study notes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo[lsp]>=0.13.0",
]

[dependency-groups]

[tool.marimo.experimental]
lsp = true
